### ISSUE TITLE
faulty handling of single-quoted strings

### ISSUE THREAD

**Issue by dimbleby** [Hubro/tree-sitter-yang#1]
Hi, saw this appear in nvim-treesitter and took it for a spin. 

Looks pretty good!  But here's a small bug for you: single-quoted strings don't contain escape sequences.  

eg see the examples at https://datatracker.ietf.org/doc/html/rfc7950#section-6.1.3.1

>     "\""  - string containing a double quote
>     '"'   - string containing a double quote
>     "\n"  - string containing a newline character
>     '\n'  - string containing a backslash followed
>             by the character n

Maybe the fix is simply to remove [this block](https://github.com/Hubro/tree-sitter-yang/blob/887204bbaff4e95bb13543d2544ebec609249d32/src/grammar.json#L426-L429)?  (but I don't know what I'm doing in treesitter, don't take my word for it).

While I'm here, I see that in your highlights query you use `@string.escape` for all sorts of things that _aren't_ string escapes; whereas most of the neovim highlighters use it for an escape sequence - which this parser doesn't expose at all...  Seems a bit back-to-front?

**Comment by Hubro** [comment]
Fixed, ref: https://github.com/Hubro/tree-sitter-yang/issues/2#issuecomment-885703238

**Comment by Hubro** [comment]
After skimming the RFC on YANG strings, it's clear that the parsing could be way better. It's been added to the TODO list in the README file.

**Comment by Hubro** [comment]
Fixed in https://github.com/Hubro/tree-sitter-yang/pull/3
