### ISSUE TITLE
suggested highlighting tweaks

### ISSUE THREAD

**Issue by dimbleby** [Hubro/tree-sitter-yang#2]
I was thinking a bit more about all the `@string.escape` per my comment in #1, and it seemed like I ought to try to offer something more constructive.

So here are some suggestions, please just close this out if you don't like them!

- `extension_keyword` could just be `@keyword`
- `yang_version` could be `@number`
- `keypath` could just be `@variable`

The ones that I struggled to fit into the neovim scheme were the `range` and `unquoted_range`.  But perhaps this is a clue that the right answer is that this should be parsed into its constituent parts, rather than as a single element: then eg the numbers in a range could be sensibly highlighted, the `..` could be sensibly highlighted.   That, I think, is what I see other languages doing with similar constructs.

Of course I realise that the range suggestion involves some work on the parser; and I have no real understanding of what it would take...

**Comment by Hubro** [comment]
> But perhaps this is a clue that the right answer is that this should be parsed into its constituent parts, rather than as a single element: then eg the numbers in a range could be sensibly highlighted, the .. could be sensibly highlighted.

That's a good idea, I'm noting that down :slightly_smiling_face: 

>I was thinking a bit more about all the @string.escape per my comment in #1, and it seemed like I ought to try to offer something more constructive.
>
>So here are some suggestions, please just close this out if you don't like them!
>
>extension_keyword could just be @keyword
>yang_version could be @number
>keypath could just be @variable

I'm aware that I'm not using the "correct" semantic highlighting groups everywhere. Most of my choices were about what looked best in the various themes I tested (nord, iceberg, ayu, gruvbox and tokyonight) while I was writing the query. When picking the highlighting groups that were closest to semantically correct, the syntax highlighting was more flat, i.e. more elements had the same color. For example, the usage of `string.escape` is for the distinct color.

I'm open to input though, do you feel that semantic correctness of the highlighting groups is more important?

**Comment by dimbleby** [comment]
> do you feel that semantic correctness of the highlighting groups is more important?

That would be my take, yes.

This is how it's "supposed" to work, if I understand rightly: parsers provide language-specific concepts, highlight queries map these to some more-or-less universal set of concepts, nvim-treesitter maps those concepts to highlight groups, colour schemes make those look good.

If we start subverting that scheme then in the long run I'd think it makes it harder to get consistent colour schemes across languages, and harder for colour scheme writers to write great schemes for treesitter-parsed languages.

If you are finding that nvim-treesitter does not provide enough richness to give the highlights that you want, I expect that the nvim-treesitter folk would be interested in that.  

Anyway, maybe worth a second opinion from them on the use of `@string.escape`?

**Comment by Hubro** [comment]
Thanks for your input @dimbleby!

I have put the last couple of days of my vacation into tree-sitter-yang and made quite a few improvements :smile:

Escape sequences in double quoted strings are now highlighted:

![image](https://user-images.githubusercontent.com/597206/126800994-30b1c256-5007-4fea-b9ad-b014cc6a433d.png)

(This still uses the string pattern copied from Javascript, so this will highlight escape sequences that are not interpreted by YANG, such as `\x45`, `\e` and so on. I couldn't be bothered to tackle that for now, the string symbol is a can of worms.)

Escape sequences are hidden from the syntax tree in single quoted strings:

![image](https://user-images.githubusercontent.com/597206/126801149-0503abe2-8376-47de-9495-f202ed05d3ab.png)

Arguments for enum statements are now always colored as strings, avoiding ugly syntax highlighting when the values are interpreted as different types:

![image](https://user-images.githubusercontent.com/597206/126798238-14e87981-49e4-4917-ab48-05f888574101.png)

Ranges are now parsed as numbers, as you suggested, and they now support multiple segments as the standard describes.

![image](https://user-images.githubusercontent.com/597206/126798357-88c664a0-2851-45d3-9906-929f00f0039a.png)

They also support the "min" and "max" keyword, which I only learned about yesterday:

![image](https://user-images.githubusercontent.com/597206/126798578-72c67516-1f13-4601-af2e-e2b8cd635fee.png)

They also work with and without quotes:

![image](https://user-images.githubusercontent.com/597206/126801568-9324ea8b-dfde-455f-9b82-1be983f904dc.png)

String arguments for the `pattern` and `must` keywords are now highlighted using `@string.special` to differentiate them from plain strings:

![image](https://user-images.githubusercontent.com/597206/126798858-d8f2f1cb-59fc-4089-af57-cb8256aa4289.png)

Import statements are now highlighted using the `@import` capture group:

![image](https://user-images.githubusercontent.com/597206/126798465-ff18b1e4-866d-4233-aa73-f1483c97dd43.png)

The value for yang-version is now always highlighted as a `@constant.builtin` and can now *only* have the values "1" and "1.1", optionally with quotes:

![image](https://user-images.githubusercontent.com/597206/126799663-d79da62d-0fa4-47ba-bddd-00d1a205962b.png)
![image](https://user-images.githubusercontent.com/597206/126799893-f1d625df-5c08-4874-8252-58d2e0cc5d8d.png)
![image](https://user-images.githubusercontent.com/597206/126799916-4ec089a6-1dd8-47d0-8b02-15a62abb5100.png)

Extension keywords are now highlighted using `@function`:

![image](https://user-images.githubusercontent.com/597206/126800358-6bc27b1b-c3ee-43a7-b02d-bf8f4c74ae84.png)

I'm still not 100% sure about that one, but I think I want it highlighted differently than built-in keywords.

Keypaths are now highlighted using `@string.special` to differentiate it from regular strings:

![image](https://user-images.githubusercontent.com/597206/126800719-b57228cc-78f9-4d3e-ace9-972e92a63c87.png)

Keypaths inside quotes are still interpreted as regular strings for now, that's an improvement for the future:

![image](https://user-images.githubusercontent.com/597206/126800803-59c2fb4d-ae9a-475c-a86e-f6af66ec8377.png)

(I just noticed I switched color schemes in the middle of taking screenshots, ignore that)

---

The highlights query now looks like this:

```scheme

(comment) @comment

; Module / submodule
["module" "submodule"] @keyword

; Keywords
(statement_keyword) @keyword
(statement_keyword "import") @include
(extension_keyword) @function

; Arguments
(built_in_type) @type.builtin
(number) @number
(boolean) @boolean
(date) @number
(range (_ ".." @operator))
(quoted_range "\"" @string)
(quoted_range "'" @string)
(yang_version) @constant.builtin
(identifier) @variable
(node_identifier) @variable
(string) @string
(string (escape_sequence) @string.escape)
(unquoted_string) @string
(keypath) @string.special

; Always highlight the value of an enum statement as a string
(enum_value) @string

; Highlight xpath and pattern strings differently from plain strings
(statement
  (statement_keyword ["pattern" "must"])
  (argument (string) @string.special))

; Punctuation
(plus_symbol) @operator
["{" "}"] @punctuation.bracket
[";"] @punctuation.delimiter
```

Let me know what you think.

**Comment by Hubro** [comment]
I just noticed I forgot to highlight the bar symbol inside ranges as an operator, fixed that now. I also decided to highlight the surrounding quotes as `@string.special`, following my convention of highlighting non-normal strings differently:

![image](https://user-images.githubusercontent.com/597206/126802519-8d936467-0856-445e-8468-18a0d937a610.png)

![image](https://user-images.githubusercontent.com/597206/126802531-1e2d9040-2666-46bc-93b6-5b9eb3f0daf6.png)

![image](https://user-images.githubusercontent.com/597206/126802544-a2b2371b-9784-4829-ac3c-48b3e8180da6.png)

I think that turned out pretty good.

**Comment by Hubro** [comment]
I also just realized `@punctuation.special` is a much better semantic fit for the punctuation inside ranges (`..` and `|`):

> `@punctuation.special` for symbols with special meaning like `{}` in string interpolation.

So I fixed that now:

```lisp
(range (_ ".." @punctuation.special))
(range (_ "|" @punctuation.special))
```

The color of the punctuation now matches the quotes (which are highlighted with `@string.special`) which I think looks better anyway.

![image](https://user-images.githubusercontent.com/597206/126804502-8f6b63a1-5d17-46bd-b37d-cfa96636e13d.png)

![image](https://user-images.githubusercontent.com/597206/126804571-edbbd534-6a2c-482e-baad-d5b75cc7eb9e.png)

![image](https://user-images.githubusercontent.com/597206/126804512-9f876a91-a6e0-47ac-a846-846e3a4ff725.png)

![image](https://user-images.githubusercontent.com/597206/126804508-df04d5ca-9e87-4b01-ad44-e6944ea957c3.png)

**Comment by dimbleby** [comment]
Very cool!  I hope you're having fun, else I'd feel terribly guilty about having encouraged you to do all this work!

A question, more for my education than because I've any objection to how the highlighting is turning out.  Why have you treated single-quoted strings as containing hidden escape sequences?  Would it not be simpler just to say that they can contain any character except another single quote, and no need to say anything about escapes at all?

Edit: actually, is it even correct to treat them as containing hidden escape sequences?  How does the parsing of something like `'this is bad\''` go?

Anyway this is looking good to me, I look forward to seeing it released.

**Comment by dimbleby** [comment]
Escape sequences in YANG are pretty straightforward, again I wouldn't know where to start in the parser, but the entire set of rules seems to be:

```
   A single-quoted string (enclosed within ' ') preserves each character
   within the quotes.  A single quote character cannot occur in a
   single-quoted string, even when preceded by a backslash.

   Within a double-quoted string (enclosed within " "), a backslash
   character introduces a representation of a special character, which
   depends on the character that immediately follows the backslash:

    \n      newline
    \t      a tab character
    \"      a double quote
    \\      a single backslash

  The backslash MUST NOT be followed by any other character.
```

and unquoted strings are similar to single-quoted strings, except I suppose that they can contain single quotes:

```
   Within an unquoted string, every character is preserved.  Note that
   this means that the backslash character does not have any special
   meaning in an unquoted string.
```

Edit: I should read more carefully, the paragraph before that lists a whole set of characters that aren't allowed in unquoted strings (and the single quote is among them)

**Comment by Hubro** [comment]
> Very cool! I hope you're having fun, else I'd feel terribly guilty about having encouraged you to do all this work!

I was tearing my hair out at times, but in hindsight it has been extremely educational and rewarding. I will probably implement more grammars if I come across any that don't already have one.

> A question, more for my education than because I've any objection to how the highlighting is turning out. Why have you treated single-quoted strings as containing hidden escape sequences? Would it not be simpler just to say that they can contain any character except another single quote, and no need to say anything about escapes at all?

Yeah I started wading into that a little bit. Single quote strings have to contain at least one escape sequence, namely `\'` as you pointed out. The way the string parsing from the JavaScript grammar works, any escape sequence that isn't recognized will instead throw an error into the syntax tree. For example, `"foo \5 bar"` will throw an error because `\5` is not parsed as an escape sequence. So if I re-define the escape sequence pattern for single quote strings to only accept `\'`, then `'this \n string'` will throw an error because `\n` is not a valid escape sequence.

I could get around that by parsing any `\...` sequence that *doesn't* match an escape sequence as a string segment instead. It looked like getting this right was going to take a lot of effort though, so I skipped it for now :smile: Just hiding the escape sequences from single quote strings was a very trivial workaround.

> 
> Edit: actually, is it even correct to treat them as containing hidden escape sequences? How does the parsing of something like `'this is bad\''` go?

Currently that will just produce `(string)`. Example from the test suite:

```yang
description "Can contain \"escaped\" double quotes";
description 'Can contain \'escaped\' single quotes';
```

```
(statement
  (statement_keyword)
  (argument
    (string
      (string_fragment)
      (escape_sequence)
      (string_fragment)
      (escape_sequence)
      (string_fragment))))
(statement
  (statement_keyword)
  (argument
    (string)))
```

> 
> Anyway this is looking good to me, I look forward to seeing it released.

It already released and merged into `nvim-treesitter`! Those guys are crazy, the pull request was merged 13 minutes after I opened it. :rocket: 

> Escape sequences in YANG are pretty straightforward, again I wouldn't know where to start in the parser, but the entire set of rules seems to be:
> 
> ```
>    A single-quoted string (enclosed within ' ') preserves each character
>    within the quotes.  A single quote character cannot occur in a
>    single-quoted string, even when preceded by a backslash.
> 
>    Within a double-quoted string (enclosed within " "), a backslash
>    character introduces a representation of a special character, which
>    depends on the character that immediately follows the backslash:
> 
>     \n      newline
>     \t      a tab character
>     \"      a double quote
>     \\      a single backslash
> 
>   The backslash MUST NOT be followed by any other character.
> ```

Added it to the official backlog :smile: 

https://github.com/Hubro/tree-sitter-yang/blob/master/README.md

I'm not sure if you use YANG on the daily, but let me know if you spot anything else that would be valuable to add. Perhaps I'll do a weekend coding binge at some point when the list gets long enough.

EDIT: Oh my, I just noticed this part: "A single quote character cannot occur in a single-quoted string, even when preceded by a backslash.". So I actually don't need to worry about escape sequences in single quote strings at all, I can just define it as `/'[^']+'/`. That's simplifies things a lot :smile: 

> 
> and unquoted strings are similar to single-quoted strings, except I suppose that they can contain single quotes:
> 
> ```
>    Within an unquoted string, every character is preserved.  Note that
>    this means that the backslash character does not have any special
>    meaning in an unquoted string.
> ```
> 
> Edit: I should read more carefully, the paragraph before that lists a whole set of characters that aren't allowed in unquoted strings (and the single quote is among them)

I often forgot that the RFC existed and only followed the ABNF grammar. The ABNF grammar wasn't very helpful when it came to unquoted strings, so I implemented it by making it handle every example that I found in the `yang-models` repository (which is a *lot*.) However, after reading the RFC is seems like I got it pretty much right :smile:

**Comment by dimbleby** [comment]
> A single quote character cannot occur in a single-quoted string, even when preceded by a backslash

Yes, that's why I thought this ought to be simpler.

I am only an occasional YANG user these days, but contributed a bit to https://github.com/nathanalderson/yang.vim when I was more active, so it is interesting to me to see how treesitter can do better.

(It's kind of surprising how _good_ a hokey collection of regex rules can be at highlighting!  But I'm definitely a believer that treesitter parsing should be more accurate, especially in corner cases).

**Comment by Hubro** [comment]
@dimbleby Very cool! Definitely let me know if you spot any situations that could be handled better. I work with YANG daily so I'm pretty invested in having good editor support :smile:
