### ISSUE TITLE
Query for patterns and must only captures some of them

### ISSUE THREAD

**Issue by dimbleby** [Hubro/tree-sitter-yang#4]
Some patterns are captured as regular `@string`, others as `@string.special`, giving inconsistent highlighting.

Eg
```yang
  typedef ipv4-address {
    type string {
      pattern
        '(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}'
      +  '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
      + '(%[\p{N}\p{L}]+)?';
    }
    description
      "The ipv4-address type represents an IPv4 address in
       dotted-quad notation.  The IPv4 address may include a zone
       index, separated by a % sign.

       The zone index is used to disambiguate identical address
       values.  For link-local addresses, the zone index will
       typically be the interface index number or the name of an
       interface.  If the zone index is not present, the default
       zone of the device will be used.

       The canonical format for the zone index is the numerical
       format";
  }
```
parses as
```
        statement [193, 4] - [198, 5]
          statement_keyword [193, 4] - [193, 8]
          argument [193, 9] - [193, 15]
            built_in_type [193, 9] - [193, 15]
          block [193, 16] - [198, 5]
            statement [194, 6] - [197, 28]
              statement_keyword [194, 6] - [194, 13]
              argument [195, 8] - [197, 27]
                string_concatenation [195, 8] - [197, 27]
                  string [195, 8] - [195, 67]
                  plus_symbol [196, 6] - [196, 7]
                  string [196, 9] - [196, 61]
                  plus_symbol [197, 6] - [197, 7]
                  string [197, 8] - [197, 27]
    ...
```
and the query for patterns doesn't spot the string concatenation.

Personally I'd be perfectly happy leaving `pattern` and `must` arguments getting the regular `@string` and just lose the special case; but maybe you're motivated to work out a more complicated query that catches them all?

**Comment by dimbleby** [comment]
FWIW: At least in the flavour of gruvbox that I use - https://github.com/lifepillar/vim-gruvbox8 - Keyword and SpecialChar both turn out red, so actually the use of `@string.special` rather reduces the visibility of these special cases rather than the opposite, making them blur into the statements that they're attached to.

But this is more of a color scheme issue than a "what's the correct highlight" issue.

Having said which: surely the appropriate group for patterns, if you do want to special case them, would be `@string.regex`?

**Comment by dimbleby** [comment]
```
(statement
  (statement_keyword "must")
  (argument (string) @string.special))
(statement
  (statement_keyword "must")
  (argument (string_concatenation (string) @string.special)))
(statement
  (statement_keyword "pattern")
  (argument (string) @string.regex))
(statement
  (statement_keyword "pattern")
  (argument (string_concatenation (string) @string.regex)))
```
maybe (though my personal preference would be not to bother for the `must` case...)

**Comment by dimbleby** [comment]
Oh and come to think of it: `when` should be treated consistently with `must` (whether as a special case or not).

**Comment by Hubro** [comment]
My motivation for highlighting them differently was to show that these are not just regular strings that can contain any value, they are strings that must contain a very specific value, like a pattern or an xpath. It's useful to disambiguate these values from free-form string values accepted by `description`, `default` and so on. `@string.special` sounds right to me, and it highlights great in all the color schemes I've tested. I'm not super invested in that position though. Do you think it would be better to highlight all strings as regular strings, regardless of context?

It should be trivial to modify the pattern string query to also target the strings inside string concatenations. Feel free to take a crack at it. If not I'll take a look when I get the time.

`when` should indeed be treated consistently, that was just an oversight on my end. There could also be other keywords that expects patterns or xpaths, I wasn't being very thorough :smile:

**Comment by dimbleby** [comment]
I'm really not sure what `@string.special` is for - there are very few other highlights queries in nvim-treesitter that use it, so I don't have a good sense of what's typical.  My take would be that a regular string is just fine for `must` and `when` and any others like 
them, but I'm also not super-invested in that position.  Maintainers get to decide such cases I guess!

I do think that `@string.regex` makes sense for `pattern`.

> Feel free to take a crack 

I already did - https://github.com/Hubro/tree-sitter-yang/issues/4#issuecomment-887793739

If I were to submit an MR it would likely be to move `pattern` to `@string.regex` and remove the use of `@string.special` for `must`.  But I didn't do that exactly because it seemed a bit opinionated and I suspected was not quite aligned with your views.

**Comment by Hubro** [comment]
String arguments to `pattern` are now highlighted as `@string.regex`, even with string concatenations.

String arguments to `must` and `when` are highlighted as `@string.special` for now, and works with string concatenations. I am leaning the way of keeping it that way for now, as I really enjoy the result.

**Comment by dimbleby** [comment]
You've gone `@string.pattern` I think you meant `@string.regex`

**Comment by Hubro** [comment]
> You've gone `@string.pattern` I think you meant `@string.regex`

I know, I fixed it immediately in the next commit :sweat_smile: Unfortunately I had already pushed.
